import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MyIFrame from "../components/MyIFrame"
import { AudioPlayer } from 'decent-audio-player';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>iframe App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Decent Audio Player
        </h1>
        <AudioPlayer size={56} audioSrc='https://nftstorage.link/ipfs/QmWNaSdhXq2WdusiBcVC2Ju5A1JJySRDVNrQMEBGcaazvC' callbackAfterPlay={console.log} active />

      </main>
    </div>
  );
};

export default Home;
